# Grafana Datasource Configuration for Njord Quant
# This file configures Prometheus as a datasource for Grafana dashboards
#
# Usage:
#   Place this file in Grafana's provisioning/datasources directory
#   Or import via Grafana UI: Configuration > Data Sources

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 5s
    version: 1

  - name: Prometheus (Production)
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 5s
    version: 1
