apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://localhost:9090
  isDefault: true
  editable: true
  jsonData:
    httpMethod: POST
    timeInterval: 5s
  version: 1
  uid: prometheus
- name: Prometheus (Production)
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: false
  editable: true
  jsonData:
    httpMethod: POST
    timeInterval: 5s
  version: 1
  uid: prometheus-prod
