version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: njord_test_redis
    ports:
      # SECURITY: Bind to localhost only (127.0.0.1), not 0.0.0.0
      - "127.0.0.1:6379:6379"
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
    internal: false  # Allow localhost binding but no external routing
