app:
  name: njord
  env: dev
  timezone: UTC

logging:
  level: INFO
  json: true
  journal_dir: ./var/log/njord

redis:
  url: "redis://127.0.0.1:6379/0"
  topics:
    trades: "md.trades.{symbol}"
    book:   "md.book.{symbol}"
    ticker: "md.ticker.{symbol}"
    intents: "strat.intent"
    risk: "risk.decision"
    orders: "exec.order"
    fills: "exec.fill"

postgres:
  dsn: "postgresql://njord:password@127.0.0.1:5432/njord"

exchange:
  venue: binanceus
  symbols: ["ATOM/USDT"]
  ws_keepalive_sec: 15

risk:
  per_order_usd_cap: 200.0
  daily_loss_usd_cap: 50.0
  orders_per_min_cap: 30
  kill_switch_file: "/var/run/njord.trading.halt"
  kill_switch_key: "njord:trading:halt"

paths:
  journal_dir: ./data/journal
  experiments_dir: ./experiments
